### ISSUE TITLE
Fighter Normal Skill names.

### ISSUE THREAD

**Issue by Jowdan3006** [SpartanVXL/DDO-Translation#2]
The fighter move that throws party members into the air, i'm unsure what to call it. Roughly translated to linking throw. Am thinking rather companion throw or simply Toss. Named it the former for now.

Also unsure as to what a certain skill does from the fighter job, The Icon is the two boots, the name translates to simply passive and the description says, "To avoid falling when it was blown away by the enemy". Am unsure what exactly this means. Is it when an enemy roars at you, that you stagger instead of falling over? Or is it when you fail a grip onto a boss monster during the yellow icon faze and have to spam L+R click?.

Edit: I think it's again the former roar one, so am going with that for now. Probs call it something like Solid Footing, Or Stable Ground.... I dunno...

**Comment by Crevox** [comment]
Yeah, that's just gonna have to be a preference/localization thing on the naming. I understand what they were going for with Linking Throw I guess, but yeah, sounds kinda weird.

I'm not positive on that fighter skill. I think that fighter skill has a button input of 3 in the description (jump?). It could be a button to perform a recovery after being knocked back/blown away. You should be able to read what it does on the famitsu wiki or the other JP wiki.

**Comment by oldmadmax** [comment]
"The fighter move that throws party members into the air, i'm unsure what to call it. Roughly translated to linking throw. Am thinking rather companion throw or simply Toss. Named it the former for now."

maybe like in DD - "Launchboard"

"Also unsure as to what a certain skill does from the fighter job, The Icon is the two boots, the name translates to simply passive and the description says, "To avoid falling when it was blown away by the enemy". Am unsure what exactly this means. Is it when an enemy roars at you, that you stagger instead of falling over? Or is it when you fail a grip onto a boss monster during the yellow icon faze and have to spam L+R click?.

i think you talking about ground recovery - when you get hit and falling you can press jump do to quick roll when hitting ground

**Comment by BananaFlambe** [comment]
Can we close this issue?
