### ISSUE TITLE
NPC Name doesn't match

### ISSUE THREAD

**Issue by BananaFlambe** [SpartanVXL/DDO-Translation#36]
In the priest tutorial quest the actual npc name and the one in the mission objective don't match.
The npc name is Lenten while in the objective is Renton

**Comment by Crevox** [comment]
I'll correct this.

What is a good romanization for the NPC name キースヒルト?

**Comment by BananaFlambe** [comment]
http://www.dd-on.jp/pc/world/npc_kieshildt.html

Kieshildt :P

**Comment by BananaFlambe** [comment]
There is an issue with a saurian name.
http://puu.sh/kyd1D/26cb00b7b0.jpg

**Comment by weisspe** [comment]
I've been seeing a lot of compound names without a space.  Most of the larger enemies in the grand mission have this issue.  Should we start putting a space before/after enemies names to combat this?

Also, how the heck is that actually the romanization of that guy's name?

**Comment by Crevox** [comment]
The named_params just need a bit of polish, because originally when they were translated, there was no designation as to whether or not things were a prefix or a suffix. This leads to the spacing issue, and some confusion.

For example, SaurianMutated could be Saurian Mutant or we could have the suffix changed to a prefix to be Mutated Saurian. The latter is probably better, but, Riftcrystal is the only one who can move the prefix to suffix and vica versa.

**Comment by weisspe** [comment]
I wasn't sure how much control we had over how things were combined.  If that's the case should we give someone the task of reviewing the named_params and updating the comments above them to indicate where they should be?  It looks like a fair amount of them may have already been updated (are marked prefix with a space after them).

**Comment by Crevox** [comment]
The problem is that we don't know the context of most of them. We can translate them, but then they can end up in the wrong place.
